version: '3.4'

services:
  webapplication:
    image: ${DOCKER_REGISTRY-}webapplication
    build:
      context: .
      dockerfile: WebApplication/Dockerfile
    depends_on:
      - db

  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
       SA_PASSWORD: "ULA2V9sPbG"
       ACCEPT_EULA: "Y"
