version: '3.4'

services:
  webapplication:
    image: webapplication
    tty: true
    ports:
      - 80:80
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    restart: on-failure
    
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
       SA_PASSWORD: "ULA2V9sPbG"
       ACCEPT_EULA: "Y"
    volumes:
      - mssql-volume:/var/opt/mssql
    ports:
      - 1433:1433

volumes:
  mssql-volume:
