version: '3.4'

services:
  webapplication:
    image: webapplication
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    restart: on-failure
    
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
       SA_PASSWORD: "ULA2V9sPbG"
       ACCEPT_EULA: "Y"

  prometheus:
    image: prom/prometheus
    restart: always
    depends_on:
      - webapplication
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    
  grafana:
    image: grafana/grafana
    depends_on:
      - prometheus
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=P@@ssw0rd1
    restart: always
    ports:
      - 3000:3000
      
