version: '3'

services:
  webapplication:
    image: webapplication
    build:
      context: .
      dockerfile: WebApplication/Dockerfile
    ports:
      - "11501:80"
    depends_on:
      - db

  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
       SA_PASSWORD: "ULA2V9sPbG"
       ACCEPT_EULA: "Y"
  integration:
    build: 
      context: .
      dockerfile: Dockerfile.integration
    depends_on:
      - webapplication
      - db         