version: '3.4'

services:
  webapplication:
    image: "docker.pkg.github.com/trivivium/devops-2k20/minitwit-group-b:latest"
    depends_on:
      - db

  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
       SA_PASSWORD: "ULA2V9sPbG"
       ACCEPT_EULA: "Y"
