global:
  scrape_interval:     5s # By default, scrape targets every 5 seconds.
  evaluation_interval: 5s # Evaluate rules every 5 seconds.

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  # external_labels:
  #   monitor: 'nats-openrmf-server'

rule_files:
  - "prometheus.rules.yml"


# A scrape configuration containing exactly one endpoint to scrape:
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'api-read-prometheus'
    static_configs:
     - targets: ["webapplication:80"]
       labels:
        group: "production"
   

