name: Release

on:
  push:
    branches:
      - master
jobs:
    release:
        name: "Release" 
        runs-on: ubuntu-latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        steps:
          - uses: rymndhng/release-on-push-action@master
            with:
              strategy: minor

    
                